---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('week3/ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26

head(ratings)
ratings |>
  count(rating) |>
  ggplot(aes(x = rating, y = n)) +
  geom_col() +
  xlab("Rating") +
  ylab("Number of Ratings")

```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean rating and number of ratings
# hint: use the n() function for easy counting within a group

ratings |>
  group_by(movie_id) |>
  summarize(mean(rating), n())

```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis

ratings |>
  group_by(movie_id) |>
  summarize(mean_rating = mean(rating), count = n()) |>
  ggplot(aes(x = count)) +
  geom_histogram(bins = 30) +
  scale_x_log10() +
  xlab("Movies") +
  ylab("Number of Ratings")


```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density

ratings |>
  group_by(movie_id) |>
  summarize(mean_rating = mean(rating), count = n()) |>
  ggplot(aes(x = mean_rating)) +
  geom_histogram(bins = 30) +
  scale_x_log10()

```

```{r cdf-movie-pop}
# rank movies by popularity (number of ratings) and compute the cdf, or fraction of all views covered by the top-k movies https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity

ratings |>
  group_by(movie_id) |>
  summarize(mean_rating = mean(rating), count = n()) |>
  arrange(desc(count)) |>
  mutate(avg_cumsum = cumsum(count) / sum(count)) |>
  mutate(rank = row_number()) |>
  ggplot(aes(x = rank, y = avg_cumsum)) +
  geom_line() +
  xlab("Rank") +
  ylab("Cumulative Property")

```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings

ratings |> 
  group_by(user_id) |>
  summarize(mean(rating), n())

```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here

ratings |> 
  group_by(user_id) |>
  summarize(mean = mean(rating), count = n()) |>
  ggplot(aes(x = user_id)) +
  geom_histogram(bins = 30) +
  scale_x_log10()

```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2a of this paper:
# note: don't worry about the "null model" lines
# just do the solid lines and dotted line (optional)
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).


library(dplyr)

movies_ranked <- ratings |>
  group_by(movie_id) |>
  count() |>
  ungroup() |>
  arrange(desc(n)) |>
  mutate(rank = row_number())

rankings_to_user <- left_join(ratings, movies_ranked, by = "movie_id")

user_max_rank <- rankings_to_user |>
  group_by(user_id) |>
  summarize(max_rank = max(rank)) |>
  arrange(max_rank)

all_k <- user_max_rank |> pull(max_rank) |> max()
satisfaction_100 <- data.frame(k = 1:all_k)
frac_satisfied <- cumsum(tabulate(user_max_rank$max_rank, nbins = all_k)) / nrow(user_max_rank)
satisfaction_100$frac_satisfied <- frac_satisfied

library(ggplot2)

ggplot(satisfaction_100, aes(x = k, y = frac_satisfied)) +
  geom_line() +
  labs(
    x = "Inventory size (top-k movies)",
    y = "Fraction of users 100% satisfied",
    title = "100% User Satisfaction Curve"
  ) +
  theme_minimal()

rank_90th <- quantile(user_max_rank$max_rank, 0.9)

satisfaction_90 <- data.frame(k = 1:rank_90th)
frac_satisfied_90 <- sapply(1:rank_90th, function(k) {
  sum(user_max_rank$max_rank <= k & user_max_rank$max_rank <= rank_90th) / nrow(user_max_rank)
})

satisfaction_90$frac_satisfied_90 <- frac_satisfied_90

ggplot(satisfaction_90, aes(x = k, y = frac_satisfied_90)) +
  geom_line() +
  labs(
    x = "Inventory size (top-k movies)",
    y = "Fraction of users 90% satisfied",
    title = "90% User Satisfaction Curve"
  ) +
  theme_minimal()

```


```{r}

# movies_ranked <- ratings |>
#   group_by(movie_id) |>
#   count() |>
#   ungroup() |>
#   arrange(desc(n)) |>
#   mutate(rank = row_number())

# ranks_to_user <- left_join(ratings, movies_ranked, by = "movie_id")
# ranks_to_user

# results <- data.frame()
# inventory_sizes <- 1:10677

# for (k in inventory_sizes) {
#   top_k_ratings <- ranks_to_user |>
#     filter(rank <= k)

#   user_top_k <- top_k_ratings |>
#     count(user_id, name = "top_k_count")

#   user_total <- ranks_to_user |>
#     count(user_id, name = "total_count") |>
#     filter(total_count >= 10)

#   user_stats <- left_join(user_total, user_top_k, by = "user_id") |>
#     mutate(top_k_count = coalesce(top_k_count, 0))

#   final_user_stats <- user_stats |>
#     mutate(ratio = top_k_count / total_count, sat_100 = as.integer(ratio == 1), sat_90  = as.integer(ratio >= 0.9))

#   avg_100 <- mean(final_user_stats$sat_100)
#   avg_90  <- mean(final_user_stats$sat_90)

#   results <- rbind(results, data.frame(k = k, frac_100 = avg_100, frac_90 = avg_90))
# }

# library(ggplot2)

# ggplot(results, aes(x = k)) +
#   geom_line(aes(y = frac_100, color = "100% Satisfied")) +
#   geom_line(aes(y = frac_90, color = "90% Satisfied")) +
#   labs(
#     title = "User Satisfaction vs Inventory Size",
#     x = "Inventory Size (k)",
#     y = "Fraction of Users Satisfied",
#     color = "Satisfaction Level"
#   ) +
#   theme_minimal()


```

